### ISSUE TITLE
dls | head

### ISSUE THREAD

**Issue by bregeon** [DIRACGrid/COMDIRAC#68]
Here is an interesting one for fun:
```
cca003:[202] dls /vo.cta.in2p3.fr/MC/PROD3/LaPalma/gamma/simtel/1759/Log/000xxx/ | head
/vo.cta.in2p3.fr/MC/PROD3/LaPalma/gamma/simtel/1759/Log/000xxx:
gamma_60deg_0deg_run1.tar.gz
gamma_60deg_0deg_run100.tar.gz
gamma_60deg_0deg_run101.tar.gz
gamma_60deg_0deg_run102.tar.gz
gamma_60deg_0deg_run103.tar.gz
gamma_60deg_0deg_run104.tar.gz
gamma_60deg_0deg_run105.tar.gz
gamma_60deg_0deg_run106.tar.gz
gamma_60deg_0deg_run107.tar.gz
Traceback (most recent call last):
  File "/sps/hep/cta/lpta/bregeon/dirac7/versions/v1r48p3_1527281009/COMDIRAC/Interfaces/scripts/dls.py", line 382, in <module>
    fccli.do_ls( optstr + p )
  File "/sps/hep/cta/lpta/bregeon/dirac7/versions/v1r48p3_1527281009/DIRAC/DataManagementSystem/Client/FileCatalogClientCLI.py", line 1201, in do_ls
    print "Error:", str(x)
IOError: [Errno 32] Broken pipe

```

**Comment by pigay** [comment]
Thanks for reporting.
It seems to happen with every Python script if used with pipes.

Here is a discussion on this: https://stackoverflow.com/questions/14207708/ioerror-errno-32-broken-pipe-python/30091579#30091579
